name: ci
on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
      - name: test
        run: CGO_ENABLED=0 go test ./...
      - name: vet
        run: CGO_ENABLED=0 go vet ./...
      - name: dist
        run: make dist
